#!/bin/sh
#
# Copyright 2019-2020 The OpenZipkin Authors
#
# Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
# in compliance with the License. You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software distributed under the License
# is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
# or implied. See the License for the specific language governing permissions and limitations under
# the License.
#

set -ue

if ! test -f docker/Dockerfile; then
  >&2 echo Please execute this script from the repository root
  exit 1
fi

docker_tag=${1?docker_tag is required. Ex openzipkin/zipkin:test}
version=${2:-}
# Ex. "module" or "exec" Empty for no classifier.
# optional classifier arg to ./build-bin/maven/maven_unjar if this image uses it. Allows you to
# define a single image that builds two classifiers, which is the case in Zipkin (slim vs normal).
maven_classifier=${MAVEN_CLASSIFIER:-}

# Avoid buildx on load for two reasons:
#  * It only supports one platform/arch on load https://github.com/docker/buildx/issues/59
#  * It would pull Docker Hub for moby/buildkit or multiarch/qemu-user-static images, using up quota
echo "Building image ${docker_tag}"
DOCKER_BUILDKIT=0 docker build --tag ${docker_tag} \
--build-arg maven_classifier=${maven_classifier} \
--build-arg version=${version} --label org.opencontainers.image.version=$version \
-f docker/Dockerfile .
