#!/bin/sh
#
# Copyright 2019-2020 The OpenZipkin Authors
#
# Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
# in compliance with the License. You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software distributed under the License
# is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
# or implied. See the License for the specific language governing permissions and limitations under
# the License.
#

set -ue

# This script sets up anything needed to deploy a SNAPSHOT or release version via `./deploy`. This
# should not assume `configure_deploy` was called at all.
#
# This script primarily helps `.travis.yml` and `RELEASE.md` contain nearly the same contents, even
# if certain OpenZipkin projects need slight adjustments here.

$(dirname "$0")/maven/configure_maven_deploy
$(dirname "$0")/docker/configure_docker_push
