#!/bin/sh
#
# Copyright 2019-2020 The OpenZipkin Authors
#
# Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
# in compliance with the License. You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software distributed under the License
# is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
# or implied. See the License for the specific language governing permissions and limitations under
# the License.
#

set -ue

# This script deploys a SNAPSHOT or release version.
#
# Note: In CI, `configure_deploy` must be called before invoking this.
#
# This script primarily helps `.travis.yml` and `RELEASE.md` contain nearly the same contents, even
# if certain OpenZipkin projects need slight adjustments here.

version=${1?version is required}

$(dirname "$0")/maven/maven_deploy ${version}

# openzipkin-contrib is named differently in docker.io (openzipkincontrib). Skip the latter for now.
export DOCKER_RELEASE_REPOS=ghcr.io
$(dirname "$0")/docker/docker_push openzipkin-contrib/zipkin-storage-kafka ${version}
