#!/bin/sh
#
# Copyright 2019-2020 The OpenZipkin Authors
#
# Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
# in compliance with the License. You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software distributed under the License
# is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
# or implied. See the License for the specific language governing permissions and limitations under
# the License.
#

set -ue

# This script deploys a SNAPSHOT or release version.
#
# Note: In CI, `configure_deploy` must be called before invoking this.
#
# This script primarily helps `.travis.yml` and `RELEASE.md` contain nearly the same contents, even
# if certain OpenZipkin projects need slight adjustments here.

# Note: the pom version should always match the git tag on release
export POM_VERSION=${POM_VERSION:-$(mvn help:evaluate -N -Dexpression=project.version -q -DforceStdout)}
release_version=${1:-${POM_VERSION}}

./mvnw --batch-mode -s ./.settings.xml -Prelease -nsu -DskipTests deploy
RELEASE_FROM_MAVEN_BUILD=true $(dirname "$0")/docker_push ${release_version}
