#!/bin/sh
#
# Copyright 2019-2020 The OpenZipkin Authors
#
# Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
# in compliance with the License. You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software distributed under the License
# is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
# or implied. See the License for the specific language governing permissions and limitations under
# the License.
#

# Fail on unset variables, but don't quit on rc!=0, so we can log what happened
set -u +e

# Like `maven_unjar`, except when the version ends in SNAPSHOT and the artifact isn't in the $PWD,
# it is built on-demand using `mvn package`.
#
# Note: Be careful building on-demand within Docker, as it can cause high bandwidth usage, pulling
# dependencies for the project without the benefit of caching

# Use b3:0 to ensure health checks aren't traced
$(dirname "$0")/maven_unjar $@
UNJAR_RC=$?

if [ "${UNJAR_RC}" == "0" ]; then exit 0; fi

case ${3?version is required} in
  *-SNAPSHOT )
    ;;
  * )
    exit ${UNJAR_RC}
    ;;
esac

set -ue

echo "*** Building snapshot from source..."
mvn -T1C -q --batch-mode -DskipTests package
exec $(dirname "$0")/maven_unjar $@
