@startuml
digraph G {
	graph [labelloc=top,label="kafka-streams topology",fontname="Verdana",fontsize=12];
	edge [fontname="Verdana",fontsize=9,labelfontname="Verdana",labelfontsize=9];
	node [fontname="Verdana",fontsize=9,shape=record];
subgraph cluster_c2 {
label = "Sub-Topology: 0";
	c0 [label="Topic: trace-spans"]
	// null
	c0 -> c3 [];
	c3 [label="Source: KSTREAM-SOURCE-0000000000"]
	c4 [label="Processor: KSTREAM-TRANSFORM-0000000001"]
	// null
	c3 -> c4 [];
	// null
	c4 -> c1 [];
	c5 [label="Sink: KSTREAM-SINK-0000000002"]
	// null
	c4 -> c5 [];
	// null
	c5 -> c0 [];
}
	c0 [label="Topic: trace-spans", shape=cds]
	c1 [label="Store: trace-store", shape=box3d]
}
@enduml