@startuml
digraph G {
	graph [labelloc=top,label="kafka-streams topology",fontname="Verdana",fontsize=12];
	edge [fontname="Verdana",fontsize=9,labelfontname="Verdana",labelfontsize=9];
	node [fontname="Verdana",fontsize=9,shape=record];
subgraph cluster_c10 {
label = "Sub-Topology: 1";
	c1 [label="Topic: traces"]
	// null
	c1 -> c11 [];
	c11 [label="Source: KSTREAM-SOURCE-0000000005"]
	c12 [label="Processor: KSTREAM-FLATMAP-0000000006"]
	// null
	c11 -> c12 [];
	c13 [label="Sink: KSTREAM-SINK-0000000007"]
	// null
	c12 -> c13 [];
	// null
	c13 -> c2 [];
}
subgraph cluster_c4 {
label = "Sub-Topology: 0";
	c0 [label="Topic: trace-spans"]
	// null
	c0 -> c5 [];
	c5 [label="Source: KSTREAM-SOURCE-0000000000"]
	c6 [label="Processor: KSTREAM-AGGREGATE-0000000001"]
	// null
	c5 -> c6 [];
	// null
	c6 -> c3 [];
	c7 [label="Processor: KTABLE-TOSTREAM-0000000002"]
	// null
	c6 -> c7 [];
	c8 [label="Processor: KSTREAM-MAP-0000000003"]
	// null
	c7 -> c8 [];
	c9 [label="Sink: KSTREAM-SINK-0000000004"]
	// null
	c8 -> c9 [];
	// null
	c9 -> c1 [];
}
	c0 [label="Topic: trace-spans", shape=cds]
	c1 [label="Topic: traces", shape=cds]
	c2 [label="Topic: dependencies", shape=cds]
	c3 [label="Store: trace-store", shape=box3d]
}
@enduml